// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqcDSVE5HJcfwvD1tQWoxH63nAjQhvY1E',
    appId: '1:257919407604:web:e24e97b5b337f97c2715a1',
    messagingSenderId: '257919407604',
    projectId: 'skiptow-worldwide',
    authDomain: 'skiptow-worldwide.firebaseapp.com',
    storageBucket: 'skiptow-worldwide.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiruDa5g7MDlGKDhJZO48TRRssAv4N7GA',
    appId: '1:257919407604:android:ae42c691509ead702715a1',
    messagingSenderId: '257919407604',
    projectId: 'skiptow-worldwide',
    storageBucket: 'skiptow-worldwide.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvH2zVpkbmQzC46atVtvbpNkp6zgRsTSE',
    appId: '1:257919407604:ios:092be6424bc0fe592715a1',
    messagingSenderId: '257919407604',
    projectId: 'skiptow-worldwide',
    storageBucket: 'skiptow-worldwide.firebasestorage.app',
    iosBundleId: 'com.skiptow.app',
  );

}